name: CI java

on:
    workflow_dispatch:
      inputs:
        run_constructor:
          description: 'Run Constructor build'
          type: choice
          options:
            - gradle
            - maven
          required: false
          default: 'maven'

jobs:
    build-ci-java-maven:
        if: ${{ github.event.inputs.run_gradle == 'maven' }}
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'adopt'
            java-version: 17

        - name: Build with Maven
          run: mvn -B package --file mavenjava17/pom.xml

        - name: Run tests
          run: mvn test --file mavenjava17/pom.xml

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
              name: build-artifact
              path: jv17/target/jv17-0.0.1-SNAPSHOT.jar

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
              name: build-artifact

        - name: Publish to GitHub Packages
          run: |
              mvn deploy:deploy-file -Dfile=jv17/target/jv17-0.0.1-SNAPSHOT.jar -DgroupId=com.example.demo -DartifactId=jv17 -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/juliobsilva/github-workflows
          env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GENERIC }}

    build-ci-gradle:
      if: ${{ github.event.inputs.run_constructor == 'gradle' }}
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlejava17/gradlew

      - name: Build with Gradle
        run: cd gradlejava17 && ./gradlew build 

      - name: Run tests
        run: cd gradlejava17 && ./gradlew test 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-gradle
          path: gradlejava17/build/libs/*.jar

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-gradle

      - name: Publish to GitHub Packages
        run: |
           cd gradlejava17 && ./gradlew publish -Drepository=github -DrepositoryUsername=${{ github.actor }} -DrepositoryPassword=$GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GENERIC }}
        