name: CI java

on:
    push:
        branches:
        - main

jobs:
    ci-java:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Java 11
          uses: actions/setup-java@v1
          with:
            distribution: 'adopt'
            java-version: 17

        - name: Build with Maven
          run: mvn -B package --file jv17/pom.xml

        - name: Run tests
          run: mvn test --file pom.xml