name: CI java

on:
    push:
        branches:
        - main

jobs:
    ci-java:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: 17

        - name: Build with Maven
          run: mvn -B package --file jv17/pom.xml

        - name: Run tests
          run: mvn test --file jv17/pom.xml

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
              name: build-artifact
              path: jv17/target/jv17-0.0.1-SNAPSHOT.jar

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
              name: build-artifact

        - name: Publish to GitHub Packages
          run: |
              mvn deploy:deploy-file -Dfile=jv17/target/jv17-0.0.1-SNAPSHOT.jar -DgroupId=com.example.avareview -DartifactId=jv17 -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/juliobsilva/github-workflows
          env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GENERIC }}
        